x-local-source: &local-source
  volumes:
    - ./local_voice_ai:/app/local_voice_ai

services:
  app:
    container_name: ivr-app
    <<: *local-source
    volumes:
      - ./local_voice_ai:/app/local_voice_ai
      - ./phonebook.csv:/app/phonebook.csv:ro
      - type: bind
        source: ${MODELS_DIR:-./models}
        target: /models

  livekit:
    container_name: ivr-livekit

  gradio:
    container_name: ivr-gradio
    <<: *local-source
    volumes:
      - ./local_voice_ai:/app/local_voice_ai
      - type: bind
        source: ${MODELS_DIR:-./models}
        target: /models

  stt:
    container_name: ivr-stt
    <<: *local-source
    volumes:
      - ./local_voice_ai:/app/local_voice_ai
      - type: bind
        source: ${MODELS_DIR:-./models}
        target: /models

  tts:
    container_name: ivr-tts
    <<: *local-source
    volumes:
      - ./local_voice_ai:/app/local_voice_ai
      - type: bind
        source: ${MODELS_DIR:-./models}
        target: /models

  llm:
    container_name: ivr-llm
